-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzxUhMyduvOCGsiVM
0ObYlEDyaF+ZoxBP/DSJ47g7m+6gCgYIKoZIzj0DAQehRANCAARif/dLQgGfBCsX
W0T+MiJatvVzKOHSe/8rFnc/phZXy1dXmtjtxIYqvhQqAcNs5FybWco24g91zqHV
PSmRRrAD
-----END PRIVATE KEY-----